### PR TITLE
Tests, Refactoring, Project Structure

### PR DESCRIPTION
**Pull request by developersworkspace**
Added the first unit test.
Changed the project structure.
Refactoring.

### CODE REVIEW

**Comment by jeske** [comment]
i would be happy to accept this pull request if you put a public domain license declaration on the files.

**Comment by developersworkspace** [comment]
I have added the license file.

**Comment by jeske** [comment]
FYI, looking more closely at this code I've noticed some bugs. I'm fixing these bugs in my tree, and I just want you to be aware of them in case you are using your code. 

(1) FileSystemRouteHandler doesn't sanitize paths, which is a security problem

(2) The concept of using a .NET unicode "string" for the response content is problematic. For example, FileSystemRouteHandler is not "8bit clean" for sending files. File.ReadAllText() uses the system default encoding to read file contents. This means it can't be used to send binary image data properly.

(3) FileSystemRouteHandler does not set a proper Content-Type header for the file, which will cause browsers to handle different file types badly

**Comment by developersworkspace** [comment]
Sure.

Im aware of the issues and will help solve them.

On Thu, Jun 30, 2016 at 9:02 PM, David Jeske notifications@github.com
wrote:

> FYI, looking more closely at this code I've noticed some bugs. I'm fixing
> these bugs in my tree, and I just want you to be aware of them in case you
> are using your code.
> 
> (1) FileSystemRouteHandler doesn't sanitize paths, which is a security
> problem
> 
> (2) The concept of using a .NET unicode "string" for the response content
> is problematic. For example, FileSystemRouteHandler is not "8bit clean" for
> sending files. File.ReadAllText() uses the system default encoding to read
> file contents. This means it can't be used to send binary image data
> properly.
> 
> (3) FileSystemRouteHandler does not set a proper Content-Type header for
> the file, which will cause browsers to handle different file types badly
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jeske/SimpleHttpServer/pull/5#issuecomment-229756662,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQmXwxQvHa1KmKpfLNs39u992tmUXuEFks5qRBK0gaJpZM4JA_DD
> .

##

**Comment by jeske** [comment]
I already checked in a fix for the bugs I listed. I also added rudamentary directory listings to FileSystemRouteHandler, and made Route dispatch extract the first match group as the request.path so the filesystem handler can be relative to the base of the match URL. 

The Respose model still requires the entire response be loaded into memory before it's sent, which isn't always a good idea. However, I like the simplicity of the response model, and this is a simple educational http server, so I think it's fine.

**Comment by developersworkspace** [comment]
Perfect.

I have added a few stuff and created another pull request.

On Thu, Jun 30, 2016 at 9:29 PM, David Jeske notifications@github.com
wrote:

> I already checked in a fix for the bugs I listed. I also added rudamentary
> directory listings to FileSystemRouteHandler, and made Route dispatch
> extract the first match group as the request.path so the filesystem handler
> can be relative to the base of the match URL.
> 
> The Respose model still requires the entire response be loaded into memory
> before it's sent, which isn't always a good idea. However, I like the
> simplicity of the response model, and this is a simple educational http
> server, so I think it's fine.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jeske/SimpleHttpServer/pull/5#issuecomment-229763808,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQmXw3Asxy9SJfVzeQvFyJ7_brQXMyWEks5qRBkqgaJpZM4JA_DD
> .

##

**Pull request merged**
